
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: First build container
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup
        run: docker build -t oma ${GITHUB_WORKSPACE}
  test:
    runs-on: ubuntu-latest
    container:
      image: oma
    name: A job to say hello
    steps:
      - name: First
        run: "Argh"
